/**
 * Swagger Banking
 * Simple Banking API used for MOIS on UHK. Api is derived from AIR bank API: https://www.airbank.cz/novinky-z-airbank/2017/open-api/open-api-banking.html#top
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michal.gregor@uhk.cz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * party account number
 */
export interface PaymentRecuringPayment { 
    firstPayment?: Date;
    lastPayment?: Date;
    interval?: PaymentRecuringPayment.IntervalEnum;
}
export namespace PaymentRecuringPayment {
    export type IntervalEnum = 'WEEK' | 'MONTH' | 'QUARTER' | 'HALF-YEAR' | 'YEAR';
    export const IntervalEnum = {
        WEEK: 'WEEK' as IntervalEnum,
        MONTH: 'MONTH' as IntervalEnum,
        QUARTER: 'QUARTER' as IntervalEnum,
        HALFYEAR: 'HALF-YEAR' as IntervalEnum,
        YEAR: 'YEAR' as IntervalEnum
    };
}
