/**
 * Swagger Banking
 * Simple Banking API used for MOIS on UHK. Api is derived from AIR bank API: https://www.airbank.cz/novinky-z-airbank/2017/open-api/open-api-banking.html#top
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michal.gregor@uhk.cz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionAdditionalInfoForeignOriginalValue } from './transactionAdditionalInfoForeignOriginalValue';


/**
 * foreign payments additional info (original value and exchange rate)
 */
export interface TransactionAdditionalInfoForeign { 
    originalValue?: TransactionAdditionalInfoForeignOriginalValue;
    /**
     * exchange rate valid at the time of transfer
     */
    exchangeRate?: number;
}
