/**
 * Swagger Banking
 * Simple Banking API used for MOIS on UHK. Api is derived from AIR bank API: https://www.airbank.cz/novinky-z-airbank/2017/open-api/open-api-banking.html#top
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michal.gregor@uhk.cz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * amount & currency in which transaction was originated
 */
export interface TransactionAdditionalInfoForeignOriginalValue { 
    /**
     * amount of money
     */
    amount: number;
    /**
     * currency of money
     */
    currency: string;
}
